### ISSUE TITLE
smartmontools aborting on recent bloody

### ISSUE THREAD

**Issue by citrus-it** [omniosorg/omnios-extra#163]
Reported by @jimklimov - it apparently did not do this until he updated bloody to the latest version;
(Jim - what version were you on before? - pkg history should tell you)

```
% pfexec /opt/ooce/sbin/smartd -d -a
smartd 6.6 2017-11-05 r4594 [i386-pc-solaris2.11] (local build)
Copyright (C) 2002-17, Bruce Allen, Christian Franke, www.smartmontools.org

=======> UNRECOGNIZED OPTION: a <=======


Use smartd -h to get a usage summary

terminate called after throwing an instance of 'int'
zsh: IOT instruction (core dumped)  pfexec /opt/ooce/sbin/smartd -d -a
```

Confirmed that this does not happen on r151026. This could be related to a change in illumos-omnios, or the new compiler in bloody.

**Comment by citrus-it** [comment]
```
#0  0xfffffc7feee6a70a in _lwp_kill () from /lib/64/libc.so.1
#1  0xfffffc7feee60fef in thr_kill () from /lib/64/libc.so.1
#2  0xfffffc7feedfd510 in raise () from /lib/64/libc.so.1
#3  0xfffffc7feedd5c18 in abort () from /lib/64/libc.so.1
#4  0xfffffc7feeb0be72 in ?? () from /usr/lib/64/libstdc++.so.6
#5  0xfffffc7feeb08cb9 in ?? () from /usr/lib/64/libstdc++.so.6
#6  0xfffffc7feeb08d01 in std::terminate() () from /usr/lib/64/libstdc++.so.6
#7  0xfffffc7feeb08f7c in __cxa_throw () from /usr/lib/64/libstdc++.so.6
#8  0x000000000043dfc0 in ParseOpts(int, char**) ()
#9  0x000000000043f2d5 in main_worker(int, char**) ()
#10 0x000000000043f93d in main ()
```

**Comment by citrus-it** [comment]
Well, this is why it's throwing an integer.
```
utility.h:#define EXIT(status) { throw (int)(status); }
```

**Comment by jimklimov** [comment]
The older one was from pre-CE setup:

````
# pkg -R /a info smartmontools
          Name: omniti/system/storage/smartmontools
       Summary: Control and monitor storage systems using SMART
         State: Installed
     Publisher: ms.omniti.com
       Version: 6.5
        Branch: 0.151014
Packaging Date: Thu Jul 14 19:12:34 2016
          Size: 2.02 MB
          FMRI: pkg://ms.omniti.com/omniti/system/storage/smartmontools@6.5-0.151014:20160714T191234Z
````

**Comment by citrus-it** [comment]
This small test program replicates the problem..

```
#include <stdio.h>

int
main()
{
        try {
                throw 1;
        } catch (int ex) {
                printf("Caught %d\n", ex);
        }
        return 0;
}
```
bloody% ./a.out
terminate called after throwing an instance of 'int'
zsh: IOT instruction (core dumped)  ./a.out
```
